version: "3"  
services:
  nginx:
    image: daocloud.io/wcpsoft/nginx:latest
    ports:
      - "80:80"
      - "443:443"
    container_name: 'php56-nginx'
    volumes:
      - /Users/ruixiangzhang/workspace/tools:/var/www/tools:rw
      - /Users/ruixiangzhang/workspace/qycloud:/var/www/qycloud:rw
      - /Users/ruixiangzhang/workspace/org:/var/www/org:rw
      - /Users/ruixiangzhang/dockerdata/nginx-conf/tools.zrx.dev.aysaas.com:/etc/nginx/sites-enabled/tools.zrx.dev.aysaas.com:ro
      - /Users/ruixiangzhang/dockerdata/nginx-conf/www.zrx.dev.aysaas.com:/etc/nginx/sites-enabled/www.zrx.dev.aysaas.com:ro
    depends_on:
      - phpcli
      - phpfpm
      - nodejs
    networks: 
      - webnet
    restart: always
  phpcli:
    image: daocloud.io/wcpsoft/php:5.6customcli
    container_name: 'php56-phpcli'
    volumes:
      - /Users/ruixiangzhang/workspace/tools:/var/www/tools:rw
      - /Users/ruixiangzhang/workspace/qycloud:/var/www/qycloud:rw
      - /Users/ruixiangzhang/workspace/org:/var/www/org:rw
    tty: true
    networks: 
      - webnet
    restart: always
  phpfpm:
    image: daocloud.io/wcpsoft/php:5.6customfpm
    container_name: 'php56-phpfpm'
    ports:
      - "9000:9000"
    volumes:
      - /Users/ruixiangzhang/workspace/tools:/var/www/tools:rw
      - /Users/ruixiangzhang/workspace/qycloud:/var/www/qycloud:rw
      - /Users/ruixiangzhang/workspace/org:/var/www/org:rw
    networks: 
      - webnet
    restart: always
  nodejs:
    image: daocloud.io/wcpsoft/nodejs:8.9.3
    container_name: 'php56-nodejs'
    volumes:
      - /Users/ruixiangzhang/workspace/tools:/var/www/tools:rw
      - /Users/ruixiangzhang/workspace/qycloud:/var/www/qycloud:rw
      - /Users/ruixiangzhang/workspace/org:/var/www/org:rw
    tty: true
    networks: 
      - webnet
    restart: always
  beanstalkd:
    image: daocloud.io/wcpsoft/beanstalkd:php56beanstalkd
    container_name: 'php56-beanstalkd'
    ports:
      - "11300:11300"
    volumes:
      - /Users/ruixiangzhang/dockerdata/beanstalkd/data:/data:rw
      - /Users/ruixiangzhang/workspace/qycloud:/var/www/qycloud:rw
      - /Users/ruixiangzhang/workspace/org:/var/www/org:rw
    networks: 
      - webnet
    tty: true
    restart: always
networks:
  webnet:
    driver: bridge