version: "3"  
services:
  redis:
    image: daocloud.io/library/redis:3.2.11-alpine
    container_name: 'redis32'
    ports:
      - "6379:6379"
    volumes:
      - /Users/ruixiangzhang/dockerdata/redis/data:/data:rw
    networks: 
      - webnet
    restart: always
networks:
  webnet:
    driver: bridge
