version: "3"  
services:
  tomcat:
    image: daocloud.io/wcpsoft/tomcat:7.0
    container_name: 'docker-tomcat'
    ports:
      - "8080:8080"
      - "5005:50005"
    volumes:
      - /Users/ruixiangzhang/workspace/sdketl/target/sdketl-0.0.1-SNAPSHOT:/usr/local/tomcat/webapps/sdketl/:rw
    extra_hosts:
      - "www.zrx.dev.aysaas.com:192.168.66.247"
      - "static.zrx.dev.aysaas.com:192.168.66.247"
      - "fileio.zrx.dev.aysaas.com:192.168.66.247"
    tty: true
    networks: 
      - webnet
    restart: always
networks:
  webnet:
    driver: bridge