version: "3"  
services:
  tomcat:
    image: daocloud.io/wcpsoft/tomcat:7.0
    container_name: 'docker-tomcat'
    ports:
      - "8080:8080"
      - "5005:50005"
    volumes:
      - /Users/ruixiangzhang/workspace/SDK/target/AnYunSDK-0.0.1-SNAPSHOT:/usr/local/tomcat/webapps/AnYunSDK/:rw
      - /Users/ruixiangzhang/dockerdata/tomcat/log:/usr/local/tomcat/logs
      - /Users/ruixiangzhang/dockerdata/tomcat/upload_anyunsdk:/usr/local/tomcat/webapps/upload_anyunsdk
    extra_hosts:
      - "www.zrx.dev.aysaas.com:10.5.4.17"
      - "static.zrx.dev.aysaas.com:10.5.4.17"
      - "fileio.zrx.dev.aysaas.com:10.5.4.17"
    tty: true
    networks: 
      - webnet
    restart: always
networks:
  webnet:
    driver: bridge