version: "3"  
services:
  nginx:
    image: daocloud.io/wcpsoft/nginx:latest
    ports:
      - "80:80"
      - "443:443"
    container_name: 'php71-nginx'
    volumes:
      - /Users/ruixiangzhang/workspace/tools:/var/www/tools:rw
      - /Users/ruixiangzhang/dockerdata/nginx-conf/tools.zrx.dev.aysaas.com:/etc/nginx/sites-enabled/tools.zrx.dev.aysaas.com:ro
    depends_on:
      - phpcli
      - phpfpm
    networks: 
      - webnet
    restart: always
  phpcli:
    image: daocloud.io/wcpsoft/php:7.1customcli
    container_name: 'php71-phpcli'
    volumes:
      - /Users/ruixiangzhang/workspace/tools:/var/www/tools:rw
      - /Users/ruixiangzhang/workspace/qycloud:/var/www/qycloud:rw
      - /Users/ruixiangzhang/workspace/org:/var/www/org:rw
      - /Users/ruixiangzhang/dockerdata/beanstalkd/data:/data:rw
    ports:
      - "11300:11300"
    tty: true
    networks: 
      - webnet
    restart: always
  phpfpm:
    image: daocloud.io/wcpsoft/php:7.1customfpm
    container_name: 'php71-phpfpm'
    ports:
      - "9000:9000"
    volumes:
      - /Users/ruixiangzhang/workspace/tools:/var/www/tools:rw
      - /Users/ruixiangzhang/workspace/qycloud:/var/www/qycloud:rw
      - /Users/ruixiangzhang/workspace/org:/var/www/org:rw
    networks: 
      - webnet
    restart: always
networks:
  webnet:
    driver: bridge