version: "3"  
services:
  nginx:
    image: daocloud.io/wcpsoft/nginx:latest
    ports:
      - "80:80"
      - "443:443"
    container_name: 'php71-nginx'
    volumes:
      - /Users/ruixiangzhang/workspace/tools:/var/www/tools:rw
      - /Users/ruixiangzhang/workspace/qycloud:/var/www/qycloud:rw
      - /Users/ruixiangzhang/workspace/org:/var/www/org:rw
      - /Users/ruixiangzhang/workspace/Node-SaaS:/var/www/Node-SaaS:rw
      - /Users/ruixiangzhang/dockerdata/nginx-conf/tools.zrx.dev.aysaas.com:/etc/nginx/sites-enabled/tools.zrx.dev.aysaas.com:ro
      - /Users/ruixiangzhang/dockerdata/nginx-conf/www.zrx.dev.aysaas.com:/etc/nginx/sites-enabled/www.zrx.dev.aysaas.com:ro
    depends_on:
      - phpcli
      - phpfpm
      - nodejs
    extra_hosts:
      - "www.zrx.dev.aysaas.com:192.168.65.40"
      - "static.zrx.dev.aysaas.com:192.168.65.40"
      - "fileio.zrx.dev.aysaas.com:192.168.65.40"
      - "nodestatic.zrx.dev.aysaas.com:192.168.65.40"
    networks: 
      - webnet
    restart: always
  phpcli:
    image: daocloud.io/wcpsoft/php:7.1customcli
    container_name: 'php71-phpcli'
    volumes:
      - /Users/ruixiangzhang/workspace/tools:/var/www/tools:rw
      - /Users/ruixiangzhang/workspace/qycloud:/var/www/qycloud:rw
      - /Users/ruixiangzhang/workspace/org:/var/www/org:rw
      - /Users/ruixiangzhang/workspace/Node-SaaS:/var/www/Node-SaaS:rw
    extra_hosts:
      - "www.zrx.dev.aysaas.com:192.168.65.40"
      - "static.zrx.dev.aysaas.com:192.168.65.40"
      - "fileio.zrx.dev.aysaas.com:192.168.65.40"
      - "nodestatic.zrx.dev.aysaas.com:192.168.65.40"
    tty: true
    networks: 
      - webnet
    restart: always
  phpfpm:
    image: daocloud.io/wcpsoft/php:7.1customfpm
    container_name: 'php71-phpfpm'
    ports:
      - "9000:9000"
    volumes:
      - /Users/ruixiangzhang/workspace/tools:/var/www/tools:rw
      - /Users/ruixiangzhang/workspace/qycloud:/var/www/qycloud:rw
      - /Users/ruixiangzhang/workspace/org:/var/www/org:rw
      - /Users/ruixiangzhang/workspace/Node-SaaS:/var/www/Node-SaaS:rw
    extra_hosts:
      - "www.zrx.dev.aysaas.com:192.168.65.40"
      - "static.zrx.dev.aysaas.com:192.168.65.40"
      - "fileio.zrx.dev.aysaas.com:192.168.65.40"
      - "nodestatic.zrx.dev.aysaas.com:192.168.65.40"
    networks: 
      - webnet
    restart: always
  nodejs:
    image: daocloud.io/wcpsoft/nodejs:8.9.3
    container_name: 'php71-nodejs'
    environment:
      NodePaaS: "/var/www/Node-SaaS"
    ports:
      - "5000:5000"
    volumes:
      - /Users/ruixiangzhang/workspace/tools:/var/www/tools:rw
      - /Users/ruixiangzhang/workspace/qycloud:/var/www/qycloud:rw
      - /Users/ruixiangzhang/workspace/org:/var/www/org:rw
      - /Users/ruixiangzhang/workspace/Node-SaaS:/var/www/Node-SaaS:rw
    extra_hosts:
      - "www.zrx.dev.aysaas.com:192.168.65.40"
      - "static.zrx.dev.aysaas.com:192.168.65.40"
      - "fileio.zrx.dev.aysaas.com:192.168.65.40"
      - "nodestatic.zrx.dev.aysaas.com:192.168.65.40"
    tty: true
    networks: 
      - webnet
    restart: always
  beanstalkd:
    image: daocloud.io/wcpsoft/beanstalkd:php71beanstalkd
    container_name: 'php71-beanstalkd'
    extra_hosts:
      - "www.zrx.dev.aysaas.com:192.168.65.40"
      - "static.zrx.dev.aysaas.com:192.168.65.40"
      - "fileio.zrx.dev.aysaas.com:192.168.65.40"
      - "nodestatic.zrx.dev.aysaas.com:192.168.65.40"
    ports:
      - "11300:11300"
    volumes:
      - /Users/ruixiangzhang/dockerdata/beanstalkd/data:/data:rw
      - /Users/ruixiangzhang/workspace/qycloud:/var/www/qycloud:rw
      - /Users/ruixiangzhang/workspace/org:/var/www/org:rw
      - /Users/ruixiangzhang/workspace/Node-SaaS:/var/www/Node-SaaS:rw
    networks: 
      - webnet
    tty: true
    restart: always
networks:
  webnet:
    driver: bridge