version: "3"  
services:
  mongodb:
    image: daocloud.io/library/mongo:3.2.16
    container_name: 'docker-mongodb'
    ports:
      - "27017:27017"
    volumes:
      - /Users/ruixiangzhang/dockerdata/mongodb/data:/data/db:rw
    networks: 
      - webnet
    restart: always
networks:
  webnet:
    driver: bridge