version: "3"  
services:
  mysql:
    image: daocloud.io/library/mysql:5.6.38
    ports:
      - "3306:3306"
    container_name: 'mysql56'
    volumes:
      - /Users/ruixiangzhang/databases:/databases:rw
      - /Users/ruixiangzhang/dockerdata/mysql56/data:/var/lib/mysql:rw
      - /Users/ruixiangzhang/dockerdata/mysql56/conf:/etc/mysql/conf.d:rw
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    networks: 
      - webnet
    restart: always
networks:
  webnet:
    driver: bridge